import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import ThemeProvider from "../src/ThemeProvider";
import ReduxProvider from "../src/redux/ReduxProvider";
import "./globals.css";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Note AI",
    description: "Generated by Note AI",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={inter.className}>
            <body suppressHydrationWarning>
                <AppRouterCacheProvider options={{ enableCssLayer: true }}>
                    <ReduxProvider>
                        <ThemeProvider>
                            <main>{children}</main>
                        </ThemeProvider>
                    </ReduxProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
