import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import ThemeProvider from "../src/ThemeProvider";
import ReduxProvider from "../src/redux/ReduxProvider";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
    title: "Note AI",
    description: "Generated by Note AI",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body suppressHydrationWarning>
                    <AppRouterCacheProvider options={{ enableCssLayer: true }}>
                        <ReduxProvider>
                            <ThemeProvider>
                                <main>{children}</main>
                            </ThemeProvider>
                        </ReduxProvider>
                    </AppRouterCacheProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
